<h2>Numpy Tutorial</h2>

In [1]:
import numpy as np

<h3>Numpy array creation</h3>

<h4>From a list</h4>

In [4]:
my_list = [1,2,3,4,5,6]
ara = np.array(my_list)

array([1, 2, 3, 4, 5, 6])

<h4>Using np.arange(start,stop,step)</h4>

In [7]:
ara = np.arange(5,30,5)
ara

array([ 5, 10, 15, 20, 25])

<h4>Using np.linspace(start,stop,number=50)</h4>

In [13]:
ara = np.linspace(1,10,10)
ara

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

<h4>Using np.ones(shape,dtype=None, order='C')///np.zeros(shape, dtype=float, order='C')</h4>

In [21]:
ara = np.zeros((2,3),dtype=int,order = 'C')
print(ara)
ara = np.ones((2,3))
ara

[[0 0 0]
 [0 0 0]]


array([[1., 1., 1.],
       [1., 1., 1.]])

<h4>Using Random.rand(shape)</h4>

In [22]:
ara = np.random.rand(3,4)
ara

array([[0.8998591 , 0.58872935, 0.29131154, 0.02238145],
       [0.71804606, 0.44868258, 0.39547536, 0.39434198],
       [0.07763713, 0.44605474, 0.23863931, 0.07719643]])

<h4>Using Random.randint(low,high,size,dtype='l')</h4>

In [25]:
ara = np.random.randint(5,10,10)
ara

array([9, 9, 7, 6, 8, 8, 6, 6, 9, 5])

<h4>Using Random.random_sample(shape)</h4>

In [28]:
ara = np.random.random_sample((2,4))
ara

array([[0.17613785, 0.86562602, 0.31946801, 0.45977057],
       [0.37327488, 0.13266426, 0.58512276, 0.71009726]])

<h3>Numpy reshape</h3>

In [30]:
my_list = [1,2,3,4,5,6]
ara = np.array(my_list).reshape(2,3)
ara

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
ara = np.arange(1,50,5).reshape(2,5)
ara

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46]])

In [37]:
ara = np.linspace(1,50,12).reshape(3,4)
ara

array([[ 1.        ,  5.45454545,  9.90909091, 14.36363636],
       [18.81818182, 23.27272727, 27.72727273, 32.18181818],
       [36.63636364, 41.09090909, 45.54545455, 50.        ]])

<h3>Applying condition on numpy array elements</h3>

In [44]:
ara = np.arange(1,50,5).reshape(2,5)
print(ara)

# Select the values according some conditions
# elements are less than 40
ara[ara<40]

[[ 1  6 11 16 21]
 [26 31 36 41 46]]


array([ 1,  6, 11, 16, 21, 26, 31, 36])

array([41, 46])