In [1]:
import pandas as pd
import numpy as np

<h3>pd.DataFrame(data_shape,index_list(names of the rows),colums_list(name of the columns)</h3>

In [2]:
df = pd.DataFrame(np.random.randint(1,10,20).reshape(4, 5), index=[
                  "Row_"+str(i) for i in range(4)], columns=["Col_"+str(i) for i in range(5)])
df.head()

Col_0  Col_1  Col_2  Col_3  Col_4
Row_0      7      8      6      9      2
Row_1      2      2      7      5      7
Row_2      6      7      2      7      4
Row_3      7      7      8      2      9

<h3>Save the DataFrame data to CSV file</h3>

In [3]:
df.to_csv('Test1.csv')

<h3>Accessing the elements</h3>
<p>For accessing every columns value just like data indexing</p>

In [4]:
# accessing all data in column 3 named col_2
print(df['Col_2'])

# for accessing multiple columns
# the column names should be like a list
print(df[['Col_1', 'Col_3']])

Row_0    6
Row_1    7
Row_2    2
Row_3    8
Name: Col_2, dtype: int64
       Col_1  Col_3
Row_0      8      9
Row_1      2      5
Row_2      7      7
Row_3      7      2


<h4>1) .loc and 2) .iloc</h4>
<p>The above twos are used for row selecting</p>

In [8]:
# .loc is used for a particular row

df.loc['Row_2']

Col_0    6
Col_1    7
Col_2    2
Col_3    7
Col_4    4
Name: Row_2, dtype: int64

In [9]:
# .iloc is used for selecting a particular row and column

df.iloc[1:4,1:3]

Col_1  Col_2
Row_1      2      7
Row_2      7      2
Row_3      7      8

<h3>Converting pandas to numpy array</h3>

In [10]:
ara = df.iloc[:,:].values
ara

array([[7, 8, 6, 9, 2],
       [2, 2, 7, 5, 7],
       [6, 7, 2, 7, 4],
       [7, 7, 8, 2, 9]])

In [11]:
ara = df.iloc[:,:].values.reshape(5,4)
ara

array([[7, 8, 6, 9],
       [2, 2, 2, 7],
       [5, 7, 6, 7],
       [2, 7, 4, 7],
       [7, 8, 2, 9]])

In [23]:
df

Col_0  Col_1  Col_2  Col_3  Col_4
Row_0      7      8      6      9      2
Row_1      2      2      7      5      7
Row_2      6      7      2      7      4
Row_3      7      7      8      2      9

<h3>Checking Null values</h3>

In [25]:
# print column with the missing values
print(df.isnull().sum())
df.isnull()

Col_0    0
Col_1    0
Col_2    0
Col_3    0
Col_4    0
dtype: int64


Col_0  Col_1  Col_2  Col_3  Col_4
Row_0  False  False  False  False  False
Row_1  False  False  False  False  False
Row_2  False  False  False  False  False
Row_3  False  False  False  False  False

<h3>Finding unique values and its frequencies</h3>

In [22]:
# unique values in a row

print(df.loc['Row_1'].unique())

# unique values with frequencies in a row
print(df.loc['Row_1'].value_counts())

# unique values in a column

print(df['Col_1'].unique())

# unique values with frequencies in a column
print(df['Col_1'].value_counts())

[2 7 5]
7    2
2    2
5    1
Name: Row_1, dtype: int64
[8 2 7]
7    2
2    1
8    1
Name: Col_1, dtype: int64


<h2> Pandas,Reading CSV files With Various Parameters</h2>
<h3>CSV</h3>
<p>By default CSV(Comma seperated Value)data is seperated by comma(,)<br>If the data is seperated with anything else(like ;)<br>then we should pass parameter <b>sep =';'</b></p>

In [37]:
df = pd.read_csv('mercedesbenz.csv')
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

<p><b>Read specific columns</b></p>

In [107]:
test_df = pd.read_csv('mercedesbenz.csv',usecols=['X0','X3'])
test_df.head()

X0 X3
0   k  a
1   k  e
2  az  c
3  az  f
4  az  f

<h3>Read Data seperated by ;</h3>

In [108]:
test_df = pd.read_csv('Test1.csv',sep=';')
test_df

Col_0  Col_1  Col_2  Col_3  Col_4
Row_0    7.0      8    6.0    9.0    NaN
Row_1    2.0      2    7.0    NaN    NaN
Row_2    6.0      7    2.0    7.0    4.0
Row_3    NaN      7    NaN    2.0    9.0

<h3>Extract loaded data description</h3>

In [109]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
col1    3 non-null object
col3    3 non-null object
dtypes: object(2)
memory usage: 128.0+ bytes
None
       col1 col3
count     3    3
unique    3    3
top       x    z
freq      1    1


In [110]:
print(test_df.info())
print(test_df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row_0 to Row_3
Data columns (total 5 columns):
Col_0    3 non-null float64
Col_1    4 non-null int64
Col_2    3 non-null float64
Col_3    3 non-null float64
Col_4    2 non-null float64
dtypes: float64(4), int64(1)
memory usage: 192.0+ bytes
None
          Col_0     Col_1     Col_2     Col_3     Col_4
count  3.000000  4.000000  3.000000  3.000000  2.000000
mean   5.000000  6.000000  5.000000  6.000000  6.500000
std    2.645751  2.708013  2.645751  3.605551  3.535534
min    2.000000  2.000000  2.000000  2.000000  4.000000
25%    4.000000  5.750000  4.000000  4.500000  5.250000
50%    6.000000  7.000000  6.000000  7.000000  6.500000
75%    6.500000  7.250000  6.500000  8.000000  7.750000
max    7.000000  8.000000  7.000000  9.000000  9.000000


In [111]:
df.isnull().sum()

col1    0
col3    0
dtype: int64

In [112]:
test_df.isnull().sum()

Col_0    1
Col_1    0
Col_2    1
Col_3    1
Col_4    2
dtype: int64

In [113]:
from io import StringIO, BytesIO

In [114]:
data = ('col1,col2,col3\n'
        'a,b,c\n'
        'x,y,z\n'
        'p,q,r\n')

print(data)
# StringIO helps to reads the entire own custom data
df = pd.read_csv(StringIO(data))
df

col1,col2,col3
a,b,c
x,y,z
p,q,r



col1 col2 col3
0    a    b    c
1    x    y    z
2    p    q    r

In [115]:
df = pd.read_csv(StringIO(data),usecols=['col1','col3'])
df

col1 col3
0    a    c
1    x    z
2    p    r

<p><b>Specifying columns data types</b></p>

In [156]:
data = ('a,b,c\n'
        '1,x,3.5\n'
        '5,y,4.5\n'
        '2,z,5.5\n')

print(data)

a,b,c
1,x,3.5
5,y,4.5
2,z,5.5



In [157]:
df = pd.read_csv(StringIO(data),dtype={'a':int,'b':str,'c':float})
df

a  b    c
0  1  x  3.5
1  5  y  4.5
2  2  z  5.5

In [158]:
df['c']

0    3.5
1    4.5
2    5.5
Name: c, dtype: float64

<p><b>Making index Specific column</b></p>

In [159]:
data = ('a,b,index,c\n'
        '1,x,1,3.5\n'
        '5,y,2,4.5\n'
        '2,z,3,5.5\n')

print(data)

a,b,index,c
1,x,1,3.5
5,y,2,4.5
2,z,3,5.5



In [160]:
df = pd.read_csv(StringIO(data))

In [161]:
df

a  b  index    c
0  1  x      1  3.5
1  5  y      2  4.5
2  2  z      3  5.5

In [164]:
# making index the 3rd column data
df = pd.read_csv(StringIO(data),index_col=2)

In [165]:
df

a  b    c
index           
1      1  x  3.5
2      5  y  4.5
3      2  z  5.5